export const paths = {
  home: '/',
  auth: { signIn: '/auth/sign-in', signUp: '/auth/sign-up', resetPassword: '/auth/reset-password' },
  dashboard: {
    overview: '/dashboard',
    account: '/dashboard/account',
    customers: '/dashboard/customers',
    integrations: '/dashboard/integrations',
    settings: '/dashboard/settings',
    users: '/dashboard/users',
    recruiters: '/dashboard/recruiters',
    questions: '/dashboard/questions',
    company: '/dashboard/company',
    packages: '/dashboard/packages',
    payments: '/dashboard/payments',
    aiMonitoring: '/dashboard/ai-monitoring',
    reports: '/dashboard/reports',
    systemSettings: '/dashboard/system-settings',
  },
  errors: { notFound: '/errors/not-found' },
} as const;
